name: Build ZIP (manual download)

on:
  workflow_dispatch: {}

jobs:
  build-zip:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Lockfile-Detection: setzt outputs.has_lock (true/false) und outputs.cache_tool (npm|yarn|none)
      - name: Detect lockfile
        id: detect_lock
        run: |
          set -euo pipefail
          if [ -f yarn.lock ]; then
            echo "has_lock=true" >> "$GITHUB_OUTPUT"
            echo "cache_tool=yarn" >> "$GITHUB_OUTPUT"
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "has_lock=true" >> "$GITHUB_OUTPUT"
            echo "cache_tool=npm" >> "$GITHUB_OUTPUT"
          else
            echo "has_lock=false" >> "$GITHUB_OUTPUT"
            echo "cache_tool=none" >> "$GITHUB_OUTPUT"
          fi

      # Setup Node MIT Cache – nur wenn ein Lockfile existiert
      - name: Setup Node (with cache)
        if: steps.detect_lock.outputs.cache_tool != 'none'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ steps.detect_lock.outputs.cache_tool }}

      # Setup Node OHNE Cache – wenn kein Lockfile existiert
      - name: Setup Node (no cache)
        if: steps.detect_lock.outputs.cache_tool == 'none'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install je nach Lockfile/Tool
      - name: Install dependencies
        run: |
          set -euo pipefail
          if [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi

      - name: Build (Vite)
        run: npm run build

      - name: SPA fallback (404 -> index)
        run: cp dist/index.html dist/404.html || true

      # Brich ab, wenn dist leer ist (sonst leeres ZIP)
      - name: Verify build output
        run: |
          set -euo pipefail
          test -d dist
          test -f dist/index.html
          COUNT="$(find dist -type f | wc -l)"
          echo "Files inside dist: $COUNT"
          [ "$COUNT" -gt 0 ]

      # Sinnvollen Artefakt-Namen bauen
      - name: Prepare artifact name
        id: meta
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          SHORT_SHA="${GITHUB_SHA::7}"
          TS="$(date -u +%Y%m%d-%H%M%SZ)"
          REPO="${GITHUB_REPOSITORY#*/}"
          FILE="site-dist-${REPO}-${REF_NAME}-${SHORT_SHA}-${TS}.zip"
          echo "ARTIFACT_FILE=$FILE" >> "$GITHUB_ENV"
          echo "ARTIFACT_NAME=${FILE%.zip}" >> "$GITHUB_ENV"
          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "name=${FILE%.zip}" >> "$GITHUB_OUTPUT"

      # ZIP mit dem *Inhalt* von dist/ (kein dist-Ordner im ZIP)
      - name: Create ZIP from dist/
        run: |
          cd dist
          zip -r "../${ARTIFACT_FILE}" .
          cd -
          ls -lh "${ARTIFACT_FILE}"

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_FILE }}
          retention-days: 14
