name: Deploy via FTP (manual, robust FTPS)

on:
  workflow_dispatch: {}

concurrency:
  group: ftp-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (no cache -> no lockfile needed)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install            # kein npm ci -> keine Lockfile nötig

      - name: Build (Vite)
        run: npm run build

      - name: SPA fallback (404 -> index)
        run: cp dist/index.html dist/404.html || true

      # ===================== VARIANTE A: EXPLIZITES FTPS (empfohlen) =====================
      - name: Deploy via FTPS (explicit, port 21)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server:     ${{ secrets.FTP_HOST }}
          username:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          protocol:   ftps            # explizites FTPS über Port 21
          port:       ${{ secrets.FTP_PORT || 21 }}
          local-dir:  dist/           # MUSS mit / enden
          # server-dir: ./            # (Root; Standard ist ./; bei Bedarf explizit setzen)
          security:   loose           # lockert TLS-Zert-Checks; bei sauberen Certs auf 'strict' stellen
          timeout:    60000           # robustere Zeitouts für trägere Hoster
          log-level:  verbose         # mehr Log für Diagnose
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            **/README.md
            **/package*.json
            **/yarn.lock
            **/pnpm-lock.yaml

      # ===================== VARIANTE B: IMPLIZITES FTPS (Port 990) =====================
      # Falls dein Hoster FTPS *implizit* nutzt (klassisch Port 990), nimm diese Variante
      # und kommentiere Variante A aus.
      # - name: Deploy via FTPS (implicit, port 990)
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      #   with:
      #     server:     ${{ secrets.FTP_HOST }}
      #     username:   ${{ secrets.FTP_USERNAME }}
      #     password:   ${{ secrets.FTP_PASSWORD }}
      #     protocol:   ftps-legacy    # implizites FTPS (siehe Doku)
      #     port:       ${{ secrets.FTP_PORT || 990 }}
      #     local-dir:  dist/
      #     # server-dir: ./
      #     security:   loose
      #     timeout:    60000
      #     log-level:  verbose
      #     exclude: |
      #       **/.git*
      #       **/.github/**
      #       node_modules/**
      #       **/README.md
      #       **/package*.json
      #       **/yarn.lock
      #       **/pnpm-lock.yaml
