name: Deploy via FTP (manual, robust FTPS)

on:
  workflow_dispatch: {}

concurrency:
  group: ftp-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      # Vite muss mit base=/endolemon/ bauen (idealerweise fix im Repo in vite.config.js)
      - name: Build (Vite with base=/endolemon/)
        run: |
          # falls base nicht gepflegt ist, setzen wir sie einmalig für den Build
          if [ -f vite.config.js ]; then
            if grep -q "base:" vite.config.js; then
              sed -i 's/base: *["'\''][^"'\'']*["'\'']\s*,/base: "\/endolemon\/",/' vite.config.js
            else
              sed -i 's/defineConfig({/defineConfig({ base: "\/endolemon\/",/' vite.config.js
            fi
          else
            echo 'import { defineConfig } from "vite"; export default defineConfig({ base: "/endolemon/", build:{ outDir:"dist" } });' > vite.config.js
          fi
          npm run build

      # nur für SPA-Deep-Links nötig (z. B. /endolemon/settings)
      - name: Add .htaccess for SPA routes (optional but recommended)
        run: |
          cat > dist/.htaccess <<'EOF'
          RewriteEngine On
          RewriteBase /endolemon/
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /endolemon/index.html [L]
          EOF

      - name: Deploy via FTPS (explicit, port 21)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server:     ${{ secrets.FTP_HOST }}
          username:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          protocol:   ftps
          port:       21
          local-dir:  dist/
          server-dir: ./                 # FTP-Account startet bereits in /endolemon
          security:   loose
          timeout:    60000
          log-level:  verbose
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            **/README.md
            **/package*.json
            **/yarn.lock
            **/pnpm-lock.yaml
            **/*.map
