name: Deploy via FTP (manual, robust FTPS)

on:
  workflow_dispatch: {}

concurrency:
  group: ftp-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (no cache -> no lockfile needed)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install            # kein npm ci -> keine Lockfile nötig

      - name: Build (Vite)
        run: npm run build

      - name: SPA fallback (404 -> index)
        run: cp dist/index.html dist/404.html || true

      # ---- Verify build output: brich ab, wenn dist leer oder index.html fehlt ----
      - name: Verify build output (fail if empty)
        run: |
          set -euo pipefail
          test -d dist
          test -f dist/index.html
          COUNT="$(find dist -type f | wc -l)"
          echo "Files inside dist: $COUNT"
          if [ "$COUNT" -eq 0 ]; then
            echo "dist ist leer – Deployment wird abgebrochen."
            exit 1
          fi
          echo "Vorschau (bis zu 50 Dateien):"
          find dist -maxdepth 2 -type f | head -n 50

      # ===================== VARIANTE A: EXPLIZITES FTPS (empfohlen) =====================
      - name: Deploy via FTPS (explicit, port 21)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server:     ${{ secrets.FTP_HOST }}
          username:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          protocol:   ftps
          # port:     ${{ secrets.FTP_PORT || 21 }}   # optional; Standard ist 21
          local-dir:  dist/                          # MUSS mit / enden
          server-dir: ./                             # Root, MUSS mit / enden
          security:   loose                          # bei sauberen Certs -> 'strict'
          timeout:    60000
          log-level:  verbose
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            **/README.md
            **/package*.json
            **/yarn.lock
            **/pnpm-lock.yaml

      # ===================== VARIANTE B: IMPLIZITES FTPS (Port 990) =====================
      # Falls dein Hoster implizites FTPS nutzt, Variante A auskommentieren und diese nutzen.
      # - name: Deploy via FTPS (implicit, port 990)
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      #   with:
      #     server:     ${{ secrets.FTP_HOST }}
      #     username:   ${{ secrets.FTP_USERNAME }}
      #     password:   ${{ secrets.FTP_PASSWORD }}
      #     protocol:   ftps-legacy
      #     # port:     ${{ secrets.FTP_PORT || 990 }}  # optional; Standard ist 990
      #     local-dir:  dist/                          # MUSS mit / enden
      #     server-dir: ./                             # Root
      #     security:   loose
      #     timeout:    60000
      #     log-level:  verbose
      #     exclude: |
      #       **/.git*
      #       **/.github/**
      #       node_modules/**
      #       **/README.md
      #       **/package*.json
      #       **/yarn.lock
      #       **/pnpm-lock.yaml
